# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 13:34
from __future__ import unicode_literals

import Field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('price', models.IntegerField(null=True)),
                ('width', models.CharField(max_length=20)),
                ('length', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Field.models.field_image_directory, verbose_name='Image')),
                ('field', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Field.Field')),
            ],
        ),
    ]
