# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Field', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='type',
        ),
        migrations.AddField(
            model_name='field',
            name='game',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='hovered',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='field',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
