# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0003_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.Field'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
