# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 15:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0004_auto_20170402_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('voted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='field',
            name='hovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='Field.Field'),
        ),
    ]
