# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0005_auto_20170403_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='value',
        ),
    ]
