# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Field', '0006_remove_vote_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='field',
        ),
        migrations.AddField(
            model_name='field',
            name='likes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='userlikes',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.Field'),
        ),
        migrations.AddField(
            model_name='userlikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
