# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0008_auto_20170409_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
